spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.102:26000/paper
    username: my_root
    password: my_root@123

mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl